/**
 * oso_web.c — OSOlogic embedded web server (mongoose.ws)
 *
 * Implements the [CORE] REST + WebSocket endpoints defined in:
 *   api/openapi/osologic-admin-api.yaml
 *   api/websocket/protocol.md
 *
 * Targets: RP2040 (lwIP + Pico SDK), STM32 (lwIP + FreeRTOS)
 *
 * Dependencies:
 *   lib/mongoose/mongoose.h   (add: git submodule add https://github.com/cesanta/mongoose lib/mongoose)
 *   core/osodb/include/osodb.h
 *   core/osoruntime/include/osoruntime.h
 *
 * Build: add mongoose.c and this file to your CMakeLists.
 *   Mongoose options (define in your CMakeLists or build flags):
 *     MG_ARCH=MG_ARCH_RP2040   or   MG_ARCH=MG_ARCH_FREERTOS
 *     MG_ENABLE_MBEDTLS=0          (no TLS on RP2040; enable on STM32H7 if needed)
 *
 * (C) Jose Roig Borrell, Roig Borrell S.L., Ibercomp S.L.
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

#include "oso_web.h"
#include "mongoose.h"

/* Forward-declared — implement in your application layer */
extern int  oso_web_on_tag_write(const char *tag_name, const char *value_json);
extern int  oso_web_on_runtime_cmd(const char *cmd);

/* ── Platform stubs (override in your BSP) ─────────────────────────────── */
#ifndef OSO_WEB_MAX_SUBS
#  define OSO_WEB_MAX_SUBS   32
#endif
#ifndef OSO_WEB_FRAME_MAX
#  define OSO_WEB_FRAME_MAX  512
#endif
#ifndef OSO_WEB_BATCH_MS
#  define OSO_WEB_BATCH_MS   50
#endif

/* Provided by BSP or weak-linked defaults */
__attribute__((weak)) uint32_t oso_uptime_s(void)        { return 0; }
__attribute__((weak)) float    oso_cpu_percent(void)      { return 0.0f; }
__attribute__((weak)) uint32_t oso_mem_used_kb(void)      { return 0; }
__attribute__((weak)) uint32_t oso_mem_total_kb(void)     { return 0; }
__attribute__((weak)) float    oso_temp_c(void)           { return -1.0f; }
__attribute__((weak)) const char *oso_device_name(void)   { return "OSOlogic"; }
__attribute__((weak)) const char *oso_firmware_ver(void)  { return "1.0.0"; }
__attribute__((weak)) const char *oso_platform_str(void)  { return "unknown"; }
__attribute__((weak)) const char *oso_ip_str(void)        { return ""; }
__attribute__((weak)) const char *oso_mac_str(void)       { return ""; }

/* ── The static HTML (generated by: xxd -i index.html > index_html.h) ──── */
/* Replace this include with your actual generated header.                  */
/* For development, mongoose can serve from the filesystem instead:         */
/*   mg_http_serve_file(c, hm, "./html/index.html", &opts);                */
#ifdef OSO_WEB_EMBED_HTML
#  include "index_html.h"   /* provides: extern const uint8_t index_html[]; extern const size_t index_html_len; */
#else
static const char index_html[] =
  "<!DOCTYPE html><html><head><title>OSOlogic</title></head>"
  "<body><p>Serve index.html from filesystem or define OSO_WEB_EMBED_HTML.</p></body></html>";
static const size_t index_html_len = sizeof(index_html) - 1;
#endif

/* ── WS subscription table ─────────────────────────────────────────────── */
typedef struct {
  struct mg_connection *conn;
  char tags[OSO_WEB_MAX_SUBS][64];  /* subscribed tag names */
  uint8_t n_tags;
  bool wildcard;                    /* true if subscribed to "*" */
} ws_client_t;

#define MAX_WS_CLIENTS 8
static ws_client_t ws_clients[MAX_WS_CLIENTS];
static struct mg_mgr s_mgr;
static bool s_running = false;

/* ── Helpers ───────────────────────────────────────────────────────────── */

static ws_client_t *find_client(struct mg_connection *c) {
  for (int i = 0; i < MAX_WS_CLIENTS; i++)
    if (ws_clients[i].conn == c) return &ws_clients[i];
  return NULL;
}

static ws_client_t *alloc_client(struct mg_connection *c) {
  for (int i = 0; i < MAX_WS_CLIENTS; i++) {
    if (!ws_clients[i].conn) {
      memset(&ws_clients[i], 0, sizeof(ws_clients[i]));
      ws_clients[i].conn = c;
      return &ws_clients[i];
    }
  }
  return NULL;
}

static void free_client(struct mg_connection *c) {
  ws_client_t *cl = find_client(c);
  if (cl) cl->conn = NULL;
}

static bool client_wants_tag(ws_client_t *cl, const char *tag_name) {
  if (cl->wildcard) return true;
  for (int i = 0; i < cl->n_tags; i++) {
    /* Simple prefix wildcard: "PLC.*" matches "PLC.Q0.0" */
    const char *pat = cl->tags[i];
    size_t plen = strlen(pat);
    if (plen > 0 && pat[plen-1] == '*') {
      if (strncmp(tag_name, pat, plen-1) == 0) return true;
    } else {
      if (strcmp(tag_name, pat) == 0) return true;
    }
  }
  return false;
}

/* Simple JSON helpers — avoids pulling in a full JSON lib */
static void json_send(struct mg_connection *c, const char *json) {
  mg_ws_send(c, json, strlen(json), WEBSOCKET_OP_TEXT);
}

/* ── REST route handlers ────────────────────────────────────────────────── */

static void handle_system_info(struct mg_connection *c) {
  char buf[256];
  mg_snprintf(buf, sizeof(buf),
    "{\"device\":\"%s\",\"firmware\":\"%s\",\"platform\":\"%s\","
    "\"uptime_s\":%lu,\"ip\":\"%s\",\"mac\":\"%s\"}",
    oso_device_name(), oso_firmware_ver(), oso_platform_str(),
    (unsigned long)oso_uptime_s(), oso_ip_str(), oso_mac_str());
  mg_http_reply(c, 200, "Content-Type: application/json\r\n", "%s", buf);
}

static void handle_system_resources(struct mg_connection *c) {
  char buf[192];
  float temp = oso_temp_c();
  if (temp < 0) {
    mg_snprintf(buf, sizeof(buf),
      "{\"cpu_pct\":%.1f,\"mem_used_kb\":%lu,\"mem_total_kb\":%lu,\"uptime_s\":%lu}",
      oso_cpu_percent(), (unsigned long)oso_mem_used_kb(),
      (unsigned long)oso_mem_total_kb(), (unsigned long)oso_uptime_s());
  } else {
    mg_snprintf(buf, sizeof(buf),
      "{\"cpu_pct\":%.1f,\"mem_used_kb\":%lu,\"mem_total_kb\":%lu,"
      "\"uptime_s\":%lu,\"temp_c\":%.1f}",
      oso_cpu_percent(), (unsigned long)oso_mem_used_kb(),
      (unsigned long)oso_mem_total_kb(), (unsigned long)oso_uptime_s(), temp);
  }
  mg_http_reply(c, 200, "Content-Type: application/json\r\n", "%s", buf);
}

/* osoruntime_status_t defined in core/osoruntime/include/osoruntime.h */
static void runtime_json(char *buf, size_t sz) {
  /* TODO: replace with real osoruntime_get_status() call */
  mg_snprintf(buf, sz,
    "{\"state\":\"stopped\",\"cycle_ms\":10,"
    "\"last_cycle_us\":0,\"cycle_count\":0,\"tasks\":[]}");
}

static void handle_runtime_status(struct mg_connection *c) {
  char buf[256];
  runtime_json(buf, sizeof(buf));
  mg_http_reply(c, 200, "Content-Type: application/json\r\n", "%s", buf);
}

static void handle_runtime_cmd(struct mg_connection *c, const char *cmd) {
  int rc = oso_web_on_runtime_cmd(cmd);
  if (rc != 0) {
    mg_http_reply(c, 409, "Content-Type: application/json\r\n",
                  "{\"error\":\"command rejected\"}");
    return;
  }
  char buf[256];
  runtime_json(buf, sizeof(buf));
  mg_http_reply(c, 200, "Content-Type: application/json\r\n", "%s", buf);
}

/* Tags: delegate to osodb. Stubs below — replace with real osodb calls. */
static void handle_tags_list(struct mg_connection *c) {
  /* TODO: iterate osodb, serialize each tag to JSON array */
  mg_http_reply(c, 200, "Content-Type: application/json\r\n", "[]");
}

static void handle_tag_get(struct mg_connection *c, const char *id_str) {
  (void)id_str;
  /* TODO: osodb_get_by_name_or_id(id_str) → JSON */
  mg_http_reply(c, 404, "Content-Type: application/json\r\n",
                "{\"error\":\"not found\"}");
}

static void handle_tag_put(struct mg_connection *c, const char *id_str,
                           struct mg_str body) {
  /* Extract tag name from id_str, pass body JSON to callback */
  char value_buf[128] = {0};
  mg_json_get_str(body, "$.value", value_buf, sizeof(value_buf));
  int rc = oso_web_on_tag_write(id_str, value_buf);
  if (rc != 0) {
    mg_http_reply(c, 400, "Content-Type: application/json\r\n",
                  "{\"error\":\"write rejected\"}");
    return;
  }
  handle_tag_get(c, id_str);
}

/* ── HTTP event handler ─────────────────────────────────────────────────── */

static void http_handler(struct mg_connection *c, int ev, void *ev_data) {
  if (ev == MG_EV_HTTP_MSG) {
    struct mg_http_message *hm = (struct mg_http_message *)ev_data;

    /* ── Serve index.html ─────────────────────────────── */
    if (mg_match(hm->uri, mg_str("/"), NULL) ||
        mg_match(hm->uri, mg_str("/index.html"), NULL)) {
      mg_http_reply(c, 200,
        "Content-Type: text/html\r\n"
        "Cache-Control: no-cache\r\n",
        "%.*s", (int)index_html_len, index_html);
      return;
    }

    /* ── Upgrade to WebSocket ─────────────────────────── */
    if (mg_match(hm->uri, mg_str("/ws"), NULL)) {
      mg_ws_upgrade(c, hm, NULL);
      alloc_client(c);
      return;
    }

    /* ── REST API ─────────────────────────────────────── */
    if (mg_match(hm->uri, mg_str("/api/v1/system/info"), NULL)) {
      handle_system_info(c);
    } else if (mg_match(hm->uri, mg_str("/api/v1/system/resources"), NULL)) {
      handle_system_resources(c);
    } else if (mg_match(hm->uri, mg_str("/api/v1/runtime/status"), NULL)) {
      handle_runtime_status(c);
    } else if (mg_match(hm->uri, mg_str("/api/v1/runtime/start"), NULL) &&
               mg_match(hm->method, mg_str("POST"), NULL)) {
      handle_runtime_cmd(c, "start");
    } else if (mg_match(hm->uri, mg_str("/api/v1/runtime/stop"), NULL) &&
               mg_match(hm->method, mg_str("POST"), NULL)) {
      handle_runtime_cmd(c, "stop");
    } else if (mg_match(hm->uri, mg_str("/api/v1/runtime/reset"), NULL) &&
               mg_match(hm->method, mg_str("POST"), NULL)) {
      handle_runtime_cmd(c, "reset");
    } else if (mg_match(hm->uri, mg_str("/api/v1/tags"), NULL) &&
               mg_match(hm->method, mg_str("GET"), NULL)) {
      handle_tags_list(c);
    } else if (mg_match(hm->uri, mg_str("/api/v1/tags/*"), NULL)) {
      /* Extract tag id: "/api/v1/tags/{id}" → last path segment */
      char id_str[64] = {0};
      const char *slash = memrchr(hm->uri.buf, '/', hm->uri.len);
      if (slash) {
        size_t id_len = hm->uri.len - (size_t)(slash + 1 - hm->uri.buf);
        if (id_len >= sizeof(id_str)) id_len = sizeof(id_str) - 1;
        memcpy(id_str, slash + 1, id_len);
      }
      if (mg_match(hm->method, mg_str("GET"), NULL)) {
        handle_tag_get(c, id_str);
      } else if (mg_match(hm->method, mg_str("PUT"), NULL)) {
        handle_tag_put(c, id_str, hm->body);
      } else {
        mg_http_reply(c, 405, "", "Method Not Allowed");
      }
    } else {
      mg_http_reply(c, 404, "", "Not Found");
    }

  } else if (ev == MG_EV_WS_MSG) {
    /* ── WebSocket incoming frame ─────────────────────── */
    struct mg_ws_message *wm = (struct mg_ws_message *)ev_data;
    ws_client_t *cl = find_client(c);
    if (!cl) return;

    /* Parse type field */
    char type_buf[32] = {0};
    mg_json_get_str(wm->data, "$.type", type_buf, sizeof(type_buf));

    if (strcmp(type_buf, "ping") == 0) {
      json_send(c, "{\"type\":\"pong\"}");

    } else if (strcmp(type_buf, "subscribe") == 0) {
      cl->n_tags = 0;
      cl->wildcard = false;
      /* tags is a JSON array of strings */
      struct mg_str arr = {0};
      int idx = mg_json_get(wm->data, "$.tags", &arr);
      if (idx > 0 && arr.len > 0) {
        /* Iterate array elements */
        for (int i = 0; ; i++) {
          char path[16];
          mg_snprintf(path, sizeof(path), "$.tags[%d]", i);
          char tag_name[64] = {0};
          if (mg_json_get_str(wm->data, path, tag_name, sizeof(tag_name)) <= 0)
            break;
          if (strcmp(tag_name, "*") == 0) {
            cl->wildcard = true;
            cl->n_tags = 0;
            break;
          }
          if (cl->n_tags < OSO_WEB_MAX_SUBS) {
            strncpy(cl->tags[cl->n_tags++], tag_name, 63);
          }
        }
      }

    } else if (strcmp(type_buf, "write") == 0) {
      char tag_name[64]   = {0};
      char value_json[64] = {0};
      mg_json_get_str(wm->data, "$.tag",   tag_name,   sizeof(tag_name));
      mg_json_get_str(wm->data, "$.value", value_json, sizeof(value_json));
      int rc = oso_web_on_tag_write(tag_name, value_json);
      if (rc == 0) {
        char ack[160];
        mg_snprintf(ack, sizeof(ack),
          "{\"type\":\"ack\",\"tag\":\"%s\",\"value\":%s}",
          tag_name, value_json);
        json_send(c, ack);
      } else {
        char err[160];
        mg_snprintf(err, sizeof(err),
          "{\"type\":\"error\",\"code\":\"TAG_NOT_FOUND\","
          "\"msg\":\"Write failed for tag: %s\"}", tag_name);
        json_send(c, err);
      }
    }

  } else if (ev == MG_EV_CLOSE) {
    free_client(c);
  }
}

/* ── Public API ─────────────────────────────────────────────────────────── */

int oso_web_init(const char *addr, uint16_t port) {
  char url[64];
  memset(ws_clients, 0, sizeof(ws_clients));
  mg_mgr_init(&s_mgr);
  mg_snprintf(url, sizeof(url), "http://%s:%u", addr, (unsigned)port);
  struct mg_connection *c = mg_http_listen(&s_mgr, url, http_handler, NULL);
  if (!c) return -1;
  s_running = true;
  return 0;
}

void oso_web_poll(uint32_t timeout_ms) {
  if (s_running) mg_mgr_poll(&s_mgr, (int)timeout_ms);
}

void oso_web_broadcast_tag(const char *tag_name,
                           const char *value_json,
                           uint64_t    ts_us) {
  /* Batch buffer: collect updates, flush every OSO_WEB_BATCH_MS */
  static char batch[OSO_WEB_FRAME_MAX];
  static int  batch_len   = 0;
  static bool batch_open  = false;
  static uint32_t batch_t = 0;

  uint32_t now = (uint32_t)(ts_us / 1000);   /* ms */

  /* Open batch frame */
  if (!batch_open) {
    batch_len = mg_snprintf(batch, sizeof(batch),
      "{\"type\":\"tag_batch\",\"updates\":[");
    batch_open = true;
    batch_t = now;
  }

  /* Append this update (if space) */
  char entry[128];
  int entry_len = mg_snprintf(entry, sizeof(entry),
    "%s{\"tag\":\"%s\",\"value\":%s,\"ts_us\":%llu}",
    batch_len > (int)sizeof("{\"type\":\"tag_batch\",\"updates\":[") ? "," : "",
    tag_name, value_json, (unsigned long long)ts_us);

  if (batch_len + entry_len + 2 < OSO_WEB_FRAME_MAX) {
    memcpy(batch + batch_len, entry, entry_len);
    batch_len += entry_len;
  }

  /* Flush if batch interval elapsed or buffer nearly full */
  bool flush = (now - batch_t >= OSO_WEB_BATCH_MS) ||
               (batch_len > OSO_WEB_FRAME_MAX - 64);

  if (flush && batch_open) {
    memcpy(batch + batch_len, "]}", 3);
    batch_len += 2;
    /* Send to all subscribed clients */
    for (int i = 0; i < MAX_WS_CLIENTS; i++) {
      ws_client_t *cl = &ws_clients[i];
      if (!cl->conn) continue;
      if (!client_wants_tag(cl, tag_name)) continue;
      mg_ws_send(cl->conn, batch, batch_len, WEBSOCKET_OP_TEXT);
    }
    batch_open = false;
    batch_len  = 0;
  }
}

void oso_web_broadcast_runtime(const char *state, uint32_t cycle_count) {
  char buf[96];
  mg_snprintf(buf, sizeof(buf),
    "{\"type\":\"runtime_event\",\"state\":\"%s\",\"cycle_count\":%lu}",
    state, (unsigned long)cycle_count);
  for (int i = 0; i < MAX_WS_CLIENTS; i++) {
    if (ws_clients[i].conn)
      mg_ws_send(ws_clients[i].conn, buf, strlen(buf), WEBSOCKET_OP_TEXT);
  }
}
