#!/usr/bin/env python3
# ============================================================
# OSOLogic — Home Assistant → osodb / DB mapper (prototype)
#
# Takes Home Assistant entities and the OSOLogic driver library
# (../drivers/*.json) and produces:
#   • osodb tag definitions (JSON)   — key, type, access, units, write service
#   • SQL for the database            — a hass_tags registry (upsert)
#
# Devices Home Assistant already supports become typed osodb tags via HA's public
# API: the driver library says how each HA domain maps, this mapper applies it per
# entity. Interoperability, not a re-implementation. Feed it a states dump (from
# hass_discover.py) or a live instance you own.
#
#   python3 hass_mapper.py --states states.json --out-json tags.json --out-sql tags.sql
#   HASS_URL=... HASS_TOKEN=... python3 hass_mapper.py --live --out-json tags.json
#
# (C) 2026 Roig Borrell S.L. · Ibercomp S.L. — AGPL-3.0-or-later
# ============================================================
import argparse
import glob
import json
import os

DRIVERS_DIR = os.path.join(os.path.dirname(__file__), "..", "drivers")


def load_drivers():
    drivers = {}
    for path in glob.glob(os.path.join(DRIVERS_DIR, "*.json")):
        d = json.load(open(path))
        drivers[d["domain"]] = d
    return drivers


def map_entity(entity, drivers):
    """One HA entity -> a list of osodb tag definitions (the entity + its attribute tags)."""
    eid = entity["entity_id"]
    domain, obj = eid.split(".", 1)
    drv = drivers.get(domain)
    if not drv:
        return []
    attrs = entity.get("attributes") or {}
    o = drv["osodb"]
    units = attrs.get(drv["units_from"]) if drv.get("units_from") else o.get("units")
    tags = [{
        "key": f"hass.{domain}.{obj}",
        "name": attrs.get("friendly_name") or obj,
        "domain": domain,
        "type": o["type"],
        "access": o["access"],
        "units": units,
        "writable": o["access"] == "ReadWrite",
        "write": drv.get("write"),
        "source": "home-assistant",
    }]
    for attr, spec in (drv.get("attributes") or {}).items():
        if attr in attrs:
            tags.append({
                "key": f"hass.{domain}.{obj}.{attr}",
                "name": f"{attrs.get('friendly_name') or obj} · {attr}",
                "domain": domain,
                "type": spec["type"],
                "access": spec["access"],
                "units": spec.get("units"),
                "writable": spec["access"] == "ReadWrite",
                "write": spec.get("write"),
                "source": "home-assistant",
            })
    return tags


def to_sql(tags):
    lines = [
        "-- osodb tag registry for Home Assistant devices (generated by hass_mapper.py)",
        "CREATE TABLE IF NOT EXISTS hass_tags (",
        "  tag_key    VARCHAR(160) PRIMARY KEY,",
        "  name       VARCHAR(200),",
        "  domain     VARCHAR(40),",
        "  data_type  VARCHAR(16),",
        "  access     VARCHAR(12),",
        "  units      VARCHAR(24),",
        "  writable   TINYINT(1)",
        ") ENGINE=InnoDB;",
        "",
    ]
    for t in tags:
        def q(v):
            return "NULL" if v is None else "'" + str(v).replace("'", "''") + "'"
        lines.append(
            "INSERT INTO hass_tags (tag_key,name,domain,data_type,access,units,writable) VALUES "
            f"({q(t['key'])},{q(t['name'])},{q(t['domain'])},{q(t['type'])},{q(t['access'])},"
            f"{q(t['units'])},{1 if t['writable'] else 0}) "
            "ON DUPLICATE KEY UPDATE name=VALUES(name),data_type=VALUES(data_type),"
            "access=VALUES(access),units=VALUES(units),writable=VALUES(writable);"
        )
    return "\n".join(lines) + "\n"


def get_states(args):
    if args.states:
        return json.load(open(args.states))
    # live
    import urllib.request
    req = urllib.request.Request(
        os.environ.get("HASS_URL", "http://homeassistant.local:8123").rstrip("/") + "/api/states",
        headers={"Authorization": "Bearer " + os.environ.get("HASS_TOKEN", "")},
    )
    with urllib.request.urlopen(req, timeout=20) as r:
        return json.load(r)


def main():
    ap = argparse.ArgumentParser(description="Map Home Assistant entities to osodb tags + DB SQL")
    ap.add_argument("--states", help="a states JSON dump (from hass_discover.py)")
    ap.add_argument("--live", action="store_true", help="fetch /api/states live (HASS_URL/HASS_TOKEN)")
    ap.add_argument("--out-json", help="write osodb tag definitions here")
    ap.add_argument("--out-sql", help="write the DB registry SQL here")
    args = ap.parse_args()
    if not args.states and not args.live:
        ap.error("give --states <file> or --live")

    drivers = load_drivers()
    states = get_states(args)
    tags = []
    for e in states:
        tags.extend(map_entity(e, drivers))

    print(f"mapped {len(states)} entities → {len(tags)} osodb tags "
          f"across {len(drivers)} drivers ({', '.join(sorted(drivers))})")
    if args.out_json:
        json.dump(tags, open(args.out_json, "w"), indent=2, ensure_ascii=False)
        print(f"  wrote {args.out_json}")
    if args.out_sql:
        open(args.out_sql, "w").write(to_sql(tags))
        print(f"  wrote {args.out_sql}")
    if not args.out_json and not args.out_sql:
        print(json.dumps(tags, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
